pwa:
    image_processor: 'pwa.image_processor.imagick'
    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'Audience Pulse'
        short_name: 'pulse'
        description: 'PWA that allows audience reaction'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: "/"
        icons:
            # https://www.veryicon.com/icons/miscellaneous/smart-site/noise-3.html
#            - src: "/images/pulse-svgrepo-com.svg"
##              sizes: [32, 48, 72, 96, 120, 128, 144, 180, 192, 256, 384, 512]
##            - src: "images/space-planet-icon.svg"
#              sizes: any

        screenshots:
        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
    serviceworker:
        enabled: false
        src: "sw.js"
        skip_waiting: true
        workbox:
#            page_caches:
#                - regex: '\/pages\/.*$'
#                  cache_name: 'static-pages'
#                  strategy: 'cacheFirst'
#                    #                  network_timeout: 2 # Wait only 2 seconds (only when strategy = networkFirst
#                  urls: # List of URLs to precache. The URL shall be comprised within the regex
##                      - 'app_terms_of_service'
##                      - 'app_about'
#                - regex: '\/articles\/.*$'
#                  cache_name: 'articles'
#                  strategy: 'staleWhileRevalidate'
#                  broadcast: true # Broadcast changes only when strategy = staleWhileRevalidate
#                  urls: # List of URLs to precache. The URL shall be comprised within the regex
##                      - 'app_articles'
##                    - 'app_about'
#            offline_fallback:
#                page: 'app_offline_page'
