survos_command:
  resource: '@SurvosCommandBundle/config/routes.yaml'
  prefix: '/admin/command'

when@dev:
  survos_command:
    resource: '@SurvosCommandBundle/config/routes.yaml'
    prefix: '/command'

